# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': '\u535a\u5ba2\u5206\u7c7b',
                'verbose_name_plural': '\u535a\u5ba2\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('img', models.ImageField(blank=True, null=True, upload_to='blog_img')),
                ('body', models.TextField(verbose_name='body')),
                ('abstract', models.TextField(blank=True, max_length=256, null=True, verbose_name='abstract')),
                ('visiting', models.PositiveIntegerField(default=0, verbose_name='visting')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='createtime')),
                ('modifyed_time', models.DateTimeField(auto_now=True, verbose_name='updatetime')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='TestModel.Category')),
            ],
            options={
                'ordering': ['-created_time'],
                'verbose_name': '\u535a\u5ba2\u6b63\u6587',
                'verbose_name_plural': '\u535a\u5ba2\u6b63\u6587',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u6807\u7b7e')),
            ],
            options={
                'verbose_name': '\u535a\u5ba2\u6807\u7b7e',
                'verbose_name_plural': '\u535a\u5ba2\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(to='TestModel.Tag'),
        ),
    ]
